#!/usr/bin/env bash
set -e

INSTALL_DIR=$HOME/HELI-X7

SCENE3D_DIR=$INSTALL_DIR/resources/environments/Scene3D

SCENE3D_LIST=$(ls -1 Scene3D/)

for scene in ${SCENE3D_LIST[@]}; do
	abs_path=$SCENE3D_DIR/$scene
	
	if [ -d $abs_path ]; then
		echo "removing $abs_path"
		rm -r $abs_path
	fi
done

exit 0
